### ISSUE TITLE
Allow all checks to return true (case: Feature Testing)

### ISSUE THREAD

**Issue by lessevv** [j-webb/laravel-unleash#19]
Mostly curious about how others think about this (or solved it). Some of the features we want to flag could be behind feature tests in our GHA pipeline. Basically, when doing these tests, we want the feature checks to always return true - without contacting our Unleash instance. I assumed that "UNLEASH_ENABLED" would do so, but this actually returns everything as false - it feels counter-intuitive.

However, suggesting a change that would flip this would break backward compatibility. Creating a new config value for it would also seem confusing. The best solution I have in mind is to check on debug mode and maybe add a config value called "PASS_ON_DEBUG" - which would maybe be less confusing.

**Comment by j-webb** [comment]
@lessevv You can achieve this without any changes to the package by using [expectations via Mockery](https://docs.mockery.io/en/latest/reference/expectations.html).

Here's an example of something you can trigger on test set up
```
Unleash::shouldReceive('isEnabled')->andReturn(true);
```

Calls to `isEnabled(...)` should now return true in your test(s).
