### ISSUE TITLE
Laravel 10 support

### ISSUE THREAD

**Issue by chrillep** [j-webb/laravel-unleash#23]

**Comment by chrillep** [comment]
@j-webb ping

**Comment by francoisauclair911** [comment]
Hi, let me know if you need help with maintenance of this package. I'd be happy to help

**Comment by j-webb** [comment]
> @j-webb ping

Apologies for the wait, merged. Also see [2.6.0](https://github.com/j-webb/laravel-unleash/releases/tag/2.6.0)


> Hi, let me know if you need help with maintenance of this package. I'd be happy to help

Thanks for the offer, I'll let you know.
